/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FilePost200Response,
} from '../models/index';
import {
    FilePost200ResponseFromJSON,
    FilePost200ResponseToJSON,
} from '../models/index';

export interface FilePostRequest {
    file: Blob;
}

/**
 * 
 */
export class FileApi extends runtime.BaseAPI {

    /**
     * 文件上传
     * 文件上传
     */
    async filePostRaw(requestParameters: FilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FilePost200Response>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling filePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FilePost200ResponseFromJSON(jsonValue));
    }

    /**
     * 文件上传
     * 文件上传
     */
    async filePost(requestParameters: FilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FilePost200Response> {
        const response = await this.filePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
