/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FilePost200Response,
  UserApiGetUserInfoByIdRequest,
  UserApiLoginRequest,
  UserApiRegisterRequest,
  UserApiSetUserInfoRequest,
  UserGetUserInfoByIdPost200Response,
  UserGetUserInfoPost200Response,
  UserLoginPost200Response,
  UserRegisterPost200Response,
  UserSetUserInfoPost200Response,
} from '../models/index';
import {
    FilePost200ResponseFromJSON,
    FilePost200ResponseToJSON,
    UserApiGetUserInfoByIdRequestFromJSON,
    UserApiGetUserInfoByIdRequestToJSON,
    UserApiLoginRequestFromJSON,
    UserApiLoginRequestToJSON,
    UserApiRegisterRequestFromJSON,
    UserApiRegisterRequestToJSON,
    UserApiSetUserInfoRequestFromJSON,
    UserApiSetUserInfoRequestToJSON,
    UserGetUserInfoByIdPost200ResponseFromJSON,
    UserGetUserInfoByIdPost200ResponseToJSON,
    UserGetUserInfoPost200ResponseFromJSON,
    UserGetUserInfoPost200ResponseToJSON,
    UserLoginPost200ResponseFromJSON,
    UserLoginPost200ResponseToJSON,
    UserRegisterPost200ResponseFromJSON,
    UserRegisterPost200ResponseToJSON,
    UserSetUserInfoPost200ResponseFromJSON,
    UserSetUserInfoPost200ResponseToJSON,
} from '../models/index';

export interface UserGetUserInfoByIdPostRequest {
    data: UserApiGetUserInfoByIdRequest;
}

export interface UserGetUserInfoPostRequest {
    data: object;
}

export interface UserLoginPostRequest {
    data: UserApiLoginRequest;
}

export interface UserRegisterPostRequest {
    data: UserApiRegisterRequest;
}

export interface UserSetUserInfoPostRequest {
    data: UserApiSetUserInfoRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * 注销
     * 注销
     */
    async logoutGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FilePost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/logout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FilePost200ResponseFromJSON(jsonValue));
    }

    /**
     * 注销
     * 注销
     */
    async logoutGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FilePost200Response> {
        const response = await this.logoutGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 获取用户信息
     * 获取用户信息
     */
    async userGetUserInfoByIdPostRaw(requestParameters: UserGetUserInfoByIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGetUserInfoByIdPost200Response>> {
        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling userGetUserInfoByIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/get_user_info_by_id`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserApiGetUserInfoByIdRequestToJSON(requestParameters['data']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserGetUserInfoByIdPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 获取用户信息
     * 获取用户信息
     */
    async userGetUserInfoByIdPost(requestParameters: UserGetUserInfoByIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGetUserInfoByIdPost200Response> {
        const response = await this.userGetUserInfoByIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 获取用户信息
     * 获取用户信息
     */
    async userGetUserInfoPostRaw(requestParameters: UserGetUserInfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserGetUserInfoPost200Response>> {
        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling userGetUserInfoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/get_user_info`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['data'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserGetUserInfoPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 获取用户信息
     * 获取用户信息
     */
    async userGetUserInfoPost(requestParameters: UserGetUserInfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserGetUserInfoPost200Response> {
        const response = await this.userGetUserInfoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 登录
     * 登录
     */
    async userLoginPostRaw(requestParameters: UserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserLoginPost200Response>> {
        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling userLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserApiLoginRequestToJSON(requestParameters['data']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 登录
     * 登录
     */
    async userLoginPost(requestParameters: UserLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserLoginPost200Response> {
        const response = await this.userLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 注册
     * 注册
     */
    async userRegisterPostRaw(requestParameters: UserRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserRegisterPost200Response>> {
        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling userRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserApiRegisterRequestToJSON(requestParameters['data']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserRegisterPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 注册
     * 注册
     */
    async userRegisterPost(requestParameters: UserRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserRegisterPost200Response> {
        const response = await this.userRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 设置用户信息
     * 设置用户信息
     */
    async userSetUserInfoPostRaw(requestParameters: UserSetUserInfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserSetUserInfoPost200Response>> {
        if (requestParameters['data'] == null) {
            throw new runtime.RequiredError(
                'data',
                'Required parameter "data" was null or undefined when calling userSetUserInfoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user/set_user_info`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserApiSetUserInfoRequestToJSON(requestParameters['data']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserSetUserInfoPost200ResponseFromJSON(jsonValue));
    }

    /**
     * 设置用户信息
     * 设置用户信息
     */
    async userSetUserInfoPost(requestParameters: UserSetUserInfoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserSetUserInfoPost200Response> {
        const response = await this.userSetUserInfoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
