/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsChapterModel } from './ModelsChapterModel';
import {
    ModelsChapterModelFromJSON,
    ModelsChapterModelFromJSONTyped,
    ModelsChapterModelToJSON,
    ModelsChapterModelToJSONTyped,
} from './ModelsChapterModel';

/**
 * 
 * @export
 * @interface CourseApiGetChapterByIDResponse
 */
export interface CourseApiGetChapterByIDResponse {
    /**
     * 
     * @type {ModelsChapterModel}
     * @memberof CourseApiGetChapterByIDResponse
     */
    chapter?: ModelsChapterModel;
}

/**
 * Check if a given object implements the CourseApiGetChapterByIDResponse interface.
 */
export function instanceOfCourseApiGetChapterByIDResponse(value: object): value is CourseApiGetChapterByIDResponse {
    return true;
}

export function CourseApiGetChapterByIDResponseFromJSON(json: any): CourseApiGetChapterByIDResponse {
    return CourseApiGetChapterByIDResponseFromJSONTyped(json, false);
}

export function CourseApiGetChapterByIDResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetChapterByIDResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter': json['chapter'] == null ? undefined : ModelsChapterModelFromJSON(json['chapter']),
    };
}

  export function CourseApiGetChapterByIDResponseToJSON(json: any): CourseApiGetChapterByIDResponse {
      return CourseApiGetChapterByIDResponseToJSONTyped(json, false);
  }

  export function CourseApiGetChapterByIDResponseToJSONTyped(value?: CourseApiGetChapterByIDResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter': ModelsChapterModelToJSON(value['chapter']),
    };
}

