/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiUpdateChapterTopicScoreRequest
 */
export interface CourseApiUpdateChapterTopicScoreRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiUpdateChapterTopicScoreRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiUpdateChapterTopicScoreRequest
     */
    conversationID?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiUpdateChapterTopicScoreRequest
     */
    topicScore?: number;
    /**
     * 废弃
     * @type {number}
     * @memberof CourseApiUpdateChapterTopicScoreRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the CourseApiUpdateChapterTopicScoreRequest interface.
 */
export function instanceOfCourseApiUpdateChapterTopicScoreRequest(value: object): value is CourseApiUpdateChapterTopicScoreRequest {
    return true;
}

export function CourseApiUpdateChapterTopicScoreRequestFromJSON(json: any): CourseApiUpdateChapterTopicScoreRequest {
    return CourseApiUpdateChapterTopicScoreRequestFromJSONTyped(json, false);
}

export function CourseApiUpdateChapterTopicScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiUpdateChapterTopicScoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'conversationID': json['conversationID'] == null ? undefined : json['conversationID'],
        'topicScore': json['topicScore'] == null ? undefined : json['topicScore'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function CourseApiUpdateChapterTopicScoreRequestToJSON(json: any): CourseApiUpdateChapterTopicScoreRequest {
      return CourseApiUpdateChapterTopicScoreRequestToJSONTyped(json, false);
  }

  export function CourseApiUpdateChapterTopicScoreRequestToJSONTyped(value?: CourseApiUpdateChapterTopicScoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'conversationID': value['conversationID'],
        'topicScore': value['topicScore'],
        'userID': value['userID'],
    };
}

