/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsCourseModel } from './ModelsCourseModel';
import {
    ModelsCourseModelFromJSON,
    ModelsCourseModelFromJSONTyped,
    ModelsCourseModelToJSON,
    ModelsCourseModelToJSONTyped,
} from './ModelsCourseModel';

/**
 * 
 * @export
 * @interface CourseApiScanAllCourseResponse
 */
export interface CourseApiScanAllCourseResponse {
    /**
     * 
     * @type {Array<ModelsCourseModel>}
     * @memberof CourseApiScanAllCourseResponse
     */
    all_course_list?: Array<ModelsCourseModel>;
}

/**
 * Check if a given object implements the CourseApiScanAllCourseResponse interface.
 */
export function instanceOfCourseApiScanAllCourseResponse(value: object): value is CourseApiScanAllCourseResponse {
    return true;
}

export function CourseApiScanAllCourseResponseFromJSON(json: any): CourseApiScanAllCourseResponse {
    return CourseApiScanAllCourseResponseFromJSONTyped(json, false);
}

export function CourseApiScanAllCourseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiScanAllCourseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'all_course_list': json['all_course_list'] == null ? undefined : ((json['all_course_list'] as Array<any>).map(ModelsCourseModelFromJSON)),
    };
}

  export function CourseApiScanAllCourseResponseToJSON(json: any): CourseApiScanAllCourseResponse {
      return CourseApiScanAllCourseResponseToJSONTyped(json, false);
  }

  export function CourseApiScanAllCourseResponseToJSONTyped(value?: CourseApiScanAllCourseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'all_course_list': value['all_course_list'] == null ? undefined : ((value['all_course_list'] as Array<any>).map(ModelsCourseModelToJSON)),
    };
}

