/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiScanCourseRequest
 */
export interface CourseApiScanCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiScanCourseRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the CourseApiScanCourseRequest interface.
 */
export function instanceOfCourseApiScanCourseRequest(value: object): value is CourseApiScanCourseRequest {
    return true;
}

export function CourseApiScanCourseRequestFromJSON(json: any): CourseApiScanCourseRequest {
    return CourseApiScanCourseRequestFromJSONTyped(json, false);
}

export function CourseApiScanCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiScanCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function CourseApiScanCourseRequestToJSON(json: any): CourseApiScanCourseRequest {
      return CourseApiScanCourseRequestToJSONTyped(json, false);
  }

  export function CourseApiScanCourseRequestToJSONTyped(value?: CourseApiScanCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userID': value['userID'],
    };
}

