/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGenChapterScoreRequest
 */
export interface CourseApiGenChapterScoreRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGenChapterScoreRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiGenChapterScoreRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the CourseApiGenChapterScoreRequest interface.
 */
export function instanceOfCourseApiGenChapterScoreRequest(value: object): value is CourseApiGenChapterScoreRequest {
    return true;
}

export function CourseApiGenChapterScoreRequestFromJSON(json: any): CourseApiGenChapterScoreRequest {
    return CourseApiGenChapterScoreRequestFromJSONTyped(json, false);
}

export function CourseApiGenChapterScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGenChapterScoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function CourseApiGenChapterScoreRequestToJSON(json: any): CourseApiGenChapterScoreRequest {
      return CourseApiGenChapterScoreRequestToJSONTyped(json, false);
  }

  export function CourseApiGenChapterScoreRequestToJSONTyped(value?: CourseApiGenChapterScoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'userID': value['userID'],
    };
}

