/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';

/**
 * 
 * @export
 * @interface CourseGenCourseFinishPost200Response
 */
export interface CourseGenCourseFinishPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseGenCourseFinishPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {object}
     * @memberof CourseGenCourseFinishPost200Response
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof CourseGenCourseFinishPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseGenCourseFinishPost200Response interface.
 */
export function instanceOfCourseGenCourseFinishPost200Response(value: object): value is CourseGenCourseFinishPost200Response {
    return true;
}

export function CourseGenCourseFinishPost200ResponseFromJSON(json: any): CourseGenCourseFinishPost200Response {
    return CourseGenCourseFinishPost200ResponseFromJSONTyped(json, false);
}

export function CourseGenCourseFinishPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseGenCourseFinishPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : json['data'],
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseGenCourseFinishPost200ResponseToJSON(json: any): CourseGenCourseFinishPost200Response {
      return CourseGenCourseFinishPost200ResponseToJSONTyped(json, false);
  }

  export function CourseGenCourseFinishPost200ResponseToJSONTyped(value?: CourseGenCourseFinishPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': value['data'],
        'msg': value['msg'],
    };
}

