/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseApiScanAllCourseResponse } from './CourseApiScanAllCourseResponse';
import {
    CourseApiScanAllCourseResponseFromJSON,
    CourseApiScanAllCourseResponseFromJSONTyped,
    CourseApiScanAllCourseResponseToJSON,
    CourseApiScanAllCourseResponseToJSONTyped,
} from './CourseApiScanAllCourseResponse';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';

/**
 * 
 * @export
 * @interface CourseScanAllCoursePost200Response
 */
export interface CourseScanAllCoursePost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseScanAllCoursePost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiScanAllCourseResponse}
     * @memberof CourseScanAllCoursePost200Response
     */
    data?: CourseApiScanAllCourseResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseScanAllCoursePost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseScanAllCoursePost200Response interface.
 */
export function instanceOfCourseScanAllCoursePost200Response(value: object): value is CourseScanAllCoursePost200Response {
    return true;
}

export function CourseScanAllCoursePost200ResponseFromJSON(json: any): CourseScanAllCoursePost200Response {
    return CourseScanAllCoursePost200ResponseFromJSONTyped(json, false);
}

export function CourseScanAllCoursePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseScanAllCoursePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiScanAllCourseResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseScanAllCoursePost200ResponseToJSON(json: any): CourseScanAllCoursePost200Response {
      return CourseScanAllCoursePost200ResponseToJSONTyped(json, false);
  }

  export function CourseScanAllCoursePost200ResponseToJSONTyped(value?: CourseScanAllCoursePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiScanAllCourseResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

