/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { CourseApiCreateChapterResponse } from './CourseApiCreateChapterResponse';
import {
    CourseApiCreateChapterResponseFromJSON,
    CourseApiCreateChapterResponseFromJSONTyped,
    CourseApiCreateChapterResponseToJSON,
    CourseApiCreateChapterResponseToJSONTyped,
} from './CourseApiCreateChapterResponse';

/**
 * 
 * @export
 * @interface CourseCreateChapterPost200Response
 */
export interface CourseCreateChapterPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseCreateChapterPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiCreateChapterResponse}
     * @memberof CourseCreateChapterPost200Response
     */
    data?: CourseApiCreateChapterResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseCreateChapterPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseCreateChapterPost200Response interface.
 */
export function instanceOfCourseCreateChapterPost200Response(value: object): value is CourseCreateChapterPost200Response {
    return true;
}

export function CourseCreateChapterPost200ResponseFromJSON(json: any): CourseCreateChapterPost200Response {
    return CourseCreateChapterPost200ResponseFromJSONTyped(json, false);
}

export function CourseCreateChapterPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseCreateChapterPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiCreateChapterResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseCreateChapterPost200ResponseToJSON(json: any): CourseCreateChapterPost200Response {
      return CourseCreateChapterPost200ResponseToJSONTyped(json, false);
  }

  export function CourseCreateChapterPost200ResponseToJSONTyped(value?: CourseCreateChapterPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiCreateChapterResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

