/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGenChapterScoreResponse
 */
export interface CourseApiGenChapterScoreResponse {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGenChapterScoreResponse
     */
    score?: number;
}

/**
 * Check if a given object implements the CourseApiGenChapterScoreResponse interface.
 */
export function instanceOfCourseApiGenChapterScoreResponse(value: object): value is CourseApiGenChapterScoreResponse {
    return true;
}

export function CourseApiGenChapterScoreResponseFromJSON(json: any): CourseApiGenChapterScoreResponse {
    return CourseApiGenChapterScoreResponseFromJSONTyped(json, false);
}

export function CourseApiGenChapterScoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGenChapterScoreResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
    };
}

  export function CourseApiGenChapterScoreResponseToJSON(json: any): CourseApiGenChapterScoreResponse {
      return CourseApiGenChapterScoreResponseToJSONTyped(json, false);
  }

  export function CourseApiGenChapterScoreResponseToJSONTyped(value?: CourseApiGenChapterScoreResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
    };
}

