/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGetChaptersRequest
 */
export interface CourseApiGetChaptersRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGetChaptersRequest
     */
    courseID?: number;
}

/**
 * Check if a given object implements the CourseApiGetChaptersRequest interface.
 */
export function instanceOfCourseApiGetChaptersRequest(value: object): value is CourseApiGetChaptersRequest {
    return true;
}

export function CourseApiGetChaptersRequestFromJSON(json: any): CourseApiGetChaptersRequest {
    return CourseApiGetChaptersRequestFromJSONTyped(json, false);
}

export function CourseApiGetChaptersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetChaptersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
    };
}

  export function CourseApiGetChaptersRequestToJSON(json: any): CourseApiGetChaptersRequest {
      return CourseApiGetChaptersRequestToJSONTyped(json, false);
  }

  export function CourseApiGetChaptersRequestToJSONTyped(value?: CourseApiGetChaptersRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
    };
}

