/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGetCourseStudentsRequest
 */
export interface CourseApiGetCourseStudentsRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGetCourseStudentsRequest
     */
    courseID?: number;
}

/**
 * Check if a given object implements the CourseApiGetCourseStudentsRequest interface.
 */
export function instanceOfCourseApiGetCourseStudentsRequest(value: object): value is CourseApiGetCourseStudentsRequest {
    return true;
}

export function CourseApiGetCourseStudentsRequestFromJSON(json: any): CourseApiGetCourseStudentsRequest {
    return CourseApiGetCourseStudentsRequestFromJSONTyped(json, false);
}

export function CourseApiGetCourseStudentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetCourseStudentsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
    };
}

  export function CourseApiGetCourseStudentsRequestToJSON(json: any): CourseApiGetCourseStudentsRequest {
      return CourseApiGetCourseStudentsRequestToJSONTyped(json, false);
  }

  export function CourseApiGetCourseStudentsRequestToJSONTyped(value?: CourseApiGetCourseStudentsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
    };
}

