/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { CourseApiGetChaptersResponse } from './CourseApiGetChaptersResponse';
import {
    CourseApiGetChaptersResponseFromJSON,
    CourseApiGetChaptersResponseFromJSONTyped,
    CourseApiGetChaptersResponseToJSON,
    CourseApiGetChaptersResponseToJSONTyped,
} from './CourseApiGetChaptersResponse';

/**
 * 
 * @export
 * @interface CourseGetChaptersPost200Response
 */
export interface CourseGetChaptersPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseGetChaptersPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiGetChaptersResponse}
     * @memberof CourseGetChaptersPost200Response
     */
    data?: CourseApiGetChaptersResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseGetChaptersPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseGetChaptersPost200Response interface.
 */
export function instanceOfCourseGetChaptersPost200Response(value: object): value is CourseGetChaptersPost200Response {
    return true;
}

export function CourseGetChaptersPost200ResponseFromJSON(json: any): CourseGetChaptersPost200Response {
    return CourseGetChaptersPost200ResponseFromJSONTyped(json, false);
}

export function CourseGetChaptersPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseGetChaptersPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiGetChaptersResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseGetChaptersPost200ResponseToJSON(json: any): CourseGetChaptersPost200Response {
      return CourseGetChaptersPost200ResponseToJSONTyped(json, false);
  }

  export function CourseGetChaptersPost200ResponseToJSONTyped(value?: CourseGetChaptersPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiGetChaptersResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

