/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsChapterModel } from './ModelsChapterModel';
import {
    ModelsChapterModelFromJSON,
    ModelsChapterModelFromJSONTyped,
    ModelsChapterModelToJSON,
    ModelsChapterModelToJSONTyped,
} from './ModelsChapterModel';

/**
 * 
 * @export
 * @interface CourseApiGetChaptersResponse
 */
export interface CourseApiGetChaptersResponse {
    /**
     * 
     * @type {Array<ModelsChapterModel>}
     * @memberof CourseApiGetChaptersResponse
     */
    chapters?: Array<ModelsChapterModel>;
}

/**
 * Check if a given object implements the CourseApiGetChaptersResponse interface.
 */
export function instanceOfCourseApiGetChaptersResponse(value: object): value is CourseApiGetChaptersResponse {
    return true;
}

export function CourseApiGetChaptersResponseFromJSON(json: any): CourseApiGetChaptersResponse {
    return CourseApiGetChaptersResponseFromJSONTyped(json, false);
}

export function CourseApiGetChaptersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetChaptersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chapters': json['chapters'] == null ? undefined : ((json['chapters'] as Array<any>).map(ModelsChapterModelFromJSON)),
    };
}

  export function CourseApiGetChaptersResponseToJSON(json: any): CourseApiGetChaptersResponse {
      return CourseApiGetChaptersResponseToJSONTyped(json, false);
  }

  export function CourseApiGetChaptersResponseToJSONTyped(value?: CourseApiGetChaptersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapters': value['chapters'] == null ? undefined : ((value['chapters'] as Array<any>).map(ModelsChapterModelToJSON)),
    };
}

