/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiJoinCourseRequest
 */
export interface CourseApiJoinCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiJoinCourseRequest
     */
    courseID?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiJoinCourseRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the CourseApiJoinCourseRequest interface.
 */
export function instanceOfCourseApiJoinCourseRequest(value: object): value is CourseApiJoinCourseRequest {
    return true;
}

export function CourseApiJoinCourseRequestFromJSON(json: any): CourseApiJoinCourseRequest {
    return CourseApiJoinCourseRequestFromJSONTyped(json, false);
}

export function CourseApiJoinCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiJoinCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function CourseApiJoinCourseRequestToJSON(json: any): CourseApiJoinCourseRequest {
      return CourseApiJoinCourseRequestToJSONTyped(json, false);
  }

  export function CourseApiJoinCourseRequestToJSONTyped(value?: CourseApiJoinCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
        'userID': value['userID'],
    };
}

