/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGetChapterByIDRequest
 */
export interface CourseApiGetChapterByIDRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGetChapterByIDRequest
     */
    chapterID?: number;
}

/**
 * Check if a given object implements the CourseApiGetChapterByIDRequest interface.
 */
export function instanceOfCourseApiGetChapterByIDRequest(value: object): value is CourseApiGetChapterByIDRequest {
    return true;
}

export function CourseApiGetChapterByIDRequestFromJSON(json: any): CourseApiGetChapterByIDRequest {
    return CourseApiGetChapterByIDRequestFromJSONTyped(json, false);
}

export function CourseApiGetChapterByIDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetChapterByIDRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
    };
}

  export function CourseApiGetChapterByIDRequestToJSON(json: any): CourseApiGetChapterByIDRequest {
      return CourseApiGetChapterByIDRequestToJSONTyped(json, false);
  }

  export function CourseApiGetChapterByIDRequestToJSONTyped(value?: CourseApiGetChapterByIDRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
    };
}

