/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';

/**
 * 
 * @export
 * @interface CourseJoinCoursePost200Response
 */
export interface CourseJoinCoursePost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseJoinCoursePost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {object}
     * @memberof CourseJoinCoursePost200Response
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof CourseJoinCoursePost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseJoinCoursePost200Response interface.
 */
export function instanceOfCourseJoinCoursePost200Response(value: object): value is CourseJoinCoursePost200Response {
    return true;
}

export function CourseJoinCoursePost200ResponseFromJSON(json: any): CourseJoinCoursePost200Response {
    return CourseJoinCoursePost200ResponseFromJSONTyped(json, false);
}

export function CourseJoinCoursePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseJoinCoursePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : json['data'],
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseJoinCoursePost200ResponseToJSON(json: any): CourseJoinCoursePost200Response {
      return CourseJoinCoursePost200ResponseToJSONTyped(json, false);
  }

  export function CourseJoinCoursePost200ResponseToJSONTyped(value?: CourseJoinCoursePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': value['data'],
        'msg': value['msg'],
    };
}

