/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiCreateConversationRequest
 */
export interface CourseApiCreateConversationRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateConversationRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateConversationRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the CourseApiCreateConversationRequest interface.
 */
export function instanceOfCourseApiCreateConversationRequest(value: object): value is CourseApiCreateConversationRequest {
    return true;
}

export function CourseApiCreateConversationRequestFromJSON(json: any): CourseApiCreateConversationRequest {
    return CourseApiCreateConversationRequestFromJSONTyped(json, false);
}

export function CourseApiCreateConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiCreateConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function CourseApiCreateConversationRequestToJSON(json: any): CourseApiCreateConversationRequest {
      return CourseApiCreateConversationRequestToJSONTyped(json, false);
  }

  export function CourseApiCreateConversationRequestToJSONTyped(value?: CourseApiCreateConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'userID': value['userID'],
    };
}

