/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseApiChapterInfo } from './CourseApiChapterInfo';
import {
    CourseApiChapterInfoFromJSON,
    CourseApiChapterInfoFromJSONTyped,
    CourseApiChapterInfoToJSON,
    CourseApiChapterInfoToJSONTyped,
} from './CourseApiChapterInfo';

/**
 * 
 * @export
 * @interface CourseApiGetChaptersByUserIDResponse
 */
export interface CourseApiGetChaptersByUserIDResponse {
    /**
     * 
     * @type {Array<CourseApiChapterInfo>}
     * @memberof CourseApiGetChaptersByUserIDResponse
     */
    chapters?: Array<CourseApiChapterInfo>;
}

/**
 * Check if a given object implements the CourseApiGetChaptersByUserIDResponse interface.
 */
export function instanceOfCourseApiGetChaptersByUserIDResponse(value: object): value is CourseApiGetChaptersByUserIDResponse {
    return true;
}

export function CourseApiGetChaptersByUserIDResponseFromJSON(json: any): CourseApiGetChaptersByUserIDResponse {
    return CourseApiGetChaptersByUserIDResponseFromJSONTyped(json, false);
}

export function CourseApiGetChaptersByUserIDResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetChaptersByUserIDResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chapters': json['chapters'] == null ? undefined : ((json['chapters'] as Array<any>).map(CourseApiChapterInfoFromJSON)),
    };
}

  export function CourseApiGetChaptersByUserIDResponseToJSON(json: any): CourseApiGetChaptersByUserIDResponse {
      return CourseApiGetChaptersByUserIDResponseToJSONTyped(json, false);
  }

  export function CourseApiGetChaptersByUserIDResponseToJSONTyped(value?: CourseApiGetChaptersByUserIDResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapters': value['chapters'] == null ? undefined : ((value['chapters'] as Array<any>).map(CourseApiChapterInfoToJSON)),
    };
}

