/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsChapterModel } from './ModelsChapterModel';
import {
    ModelsChapterModelFromJSON,
    ModelsChapterModelFromJSONTyped,
    ModelsChapterModelToJSON,
    ModelsChapterModelToJSONTyped,
} from './ModelsChapterModel';

/**
 * 
 * @export
 * @interface CourseApiUpdateChapterRequest
 */
export interface CourseApiUpdateChapterRequest {
    /**
     * 
     * @type {ModelsChapterModel}
     * @memberof CourseApiUpdateChapterRequest
     */
    chapter?: ModelsChapterModel;
}

/**
 * Check if a given object implements the CourseApiUpdateChapterRequest interface.
 */
export function instanceOfCourseApiUpdateChapterRequest(value: object): value is CourseApiUpdateChapterRequest {
    return true;
}

export function CourseApiUpdateChapterRequestFromJSON(json: any): CourseApiUpdateChapterRequest {
    return CourseApiUpdateChapterRequestFromJSONTyped(json, false);
}

export function CourseApiUpdateChapterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiUpdateChapterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter': json['chapter'] == null ? undefined : ModelsChapterModelFromJSON(json['chapter']),
    };
}

  export function CourseApiUpdateChapterRequestToJSON(json: any): CourseApiUpdateChapterRequest {
      return CourseApiUpdateChapterRequestToJSONTyped(json, false);
  }

  export function CourseApiUpdateChapterRequestToJSONTyped(value?: CourseApiUpdateChapterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter': ModelsChapterModelToJSON(value['chapter']),
    };
}

