/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsChapterModel } from './ModelsChapterModel';
import {
    ModelsChapterModelFromJSON,
    ModelsChapterModelFromJSONTyped,
    ModelsChapterModelToJSON,
    ModelsChapterModelToJSONTyped,
} from './ModelsChapterModel';

/**
 * 
 * @export
 * @interface CourseApiChapterInfo
 */
export interface CourseApiChapterInfo {
    /**
     * 
     * @type {ModelsChapterModel}
     * @memberof CourseApiChapterInfo
     */
    chapter?: ModelsChapterModel;
    /**
     * 
     * @type {number}
     * @memberof CourseApiChapterInfo
     */
    score?: number;
}

/**
 * Check if a given object implements the CourseApiChapterInfo interface.
 */
export function instanceOfCourseApiChapterInfo(value: object): value is CourseApiChapterInfo {
    return true;
}

export function CourseApiChapterInfoFromJSON(json: any): CourseApiChapterInfo {
    return CourseApiChapterInfoFromJSONTyped(json, false);
}

export function CourseApiChapterInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiChapterInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter': json['chapter'] == null ? undefined : ModelsChapterModelFromJSON(json['chapter']),
        'score': json['score'] == null ? undefined : json['score'],
    };
}

  export function CourseApiChapterInfoToJSON(json: any): CourseApiChapterInfo {
      return CourseApiChapterInfoToJSONTyped(json, false);
  }

  export function CourseApiChapterInfoToJSONTyped(value?: CourseApiChapterInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter': ModelsChapterModelToJSON(value['chapter']),
        'score': value['score'],
    };
}

