/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiCreateCourseRequest
 */
export interface CourseApiCreateCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateCourseRequest
     */
    createrID?: number;
}

/**
 * Check if a given object implements the CourseApiCreateCourseRequest interface.
 */
export function instanceOfCourseApiCreateCourseRequest(value: object): value is CourseApiCreateCourseRequest {
    return true;
}

export function CourseApiCreateCourseRequestFromJSON(json: any): CourseApiCreateCourseRequest {
    return CourseApiCreateCourseRequestFromJSONTyped(json, false);
}

export function CourseApiCreateCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiCreateCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createrID': json['createrID'] == null ? undefined : json['createrID'],
    };
}

  export function CourseApiCreateCourseRequestToJSON(json: any): CourseApiCreateCourseRequest {
      return CourseApiCreateCourseRequestToJSONTyped(json, false);
  }

  export function CourseApiCreateCourseRequestToJSONTyped(value?: CourseApiCreateCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createrID': value['createrID'],
    };
}

