/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGetCourseRequest
 */
export interface CourseApiGetCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGetCourseRequest
     */
    courseID?: number;
}

/**
 * Check if a given object implements the CourseApiGetCourseRequest interface.
 */
export function instanceOfCourseApiGetCourseRequest(value: object): value is CourseApiGetCourseRequest {
    return true;
}

export function CourseApiGetCourseRequestFromJSON(json: any): CourseApiGetCourseRequest {
    return CourseApiGetCourseRequestFromJSONTyped(json, false);
}

export function CourseApiGetCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
    };
}

  export function CourseApiGetCourseRequestToJSON(json: any): CourseApiGetCourseRequest {
      return CourseApiGetCourseRequestToJSONTyped(json, false);
  }

  export function CourseApiGetCourseRequestToJSONTyped(value?: CourseApiGetCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
    };
}

