/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiCreateChapterResponse
 */
export interface CourseApiCreateChapterResponse {
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateChapterResponse
     */
    chapterID?: number;
}

/**
 * Check if a given object implements the CourseApiCreateChapterResponse interface.
 */
export function instanceOfCourseApiCreateChapterResponse(value: object): value is CourseApiCreateChapterResponse {
    return true;
}

export function CourseApiCreateChapterResponseFromJSON(json: any): CourseApiCreateChapterResponse {
    return CourseApiCreateChapterResponseFromJSONTyped(json, false);
}

export function CourseApiCreateChapterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiCreateChapterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
    };
}

  export function CourseApiCreateChapterResponseToJSON(json: any): CourseApiCreateChapterResponse {
      return CourseApiCreateChapterResponseToJSONTyped(json, false);
  }

  export function CourseApiCreateChapterResponseToJSONTyped(value?: CourseApiCreateChapterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
    };
}

