/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiDeleteChapterRequest
 */
export interface CourseApiDeleteChapterRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiDeleteChapterRequest
     */
    chapterID?: number;
}

/**
 * Check if a given object implements the CourseApiDeleteChapterRequest interface.
 */
export function instanceOfCourseApiDeleteChapterRequest(value: object): value is CourseApiDeleteChapterRequest {
    return true;
}

export function CourseApiDeleteChapterRequestFromJSON(json: any): CourseApiDeleteChapterRequest {
    return CourseApiDeleteChapterRequestFromJSONTyped(json, false);
}

export function CourseApiDeleteChapterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiDeleteChapterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
    };
}

  export function CourseApiDeleteChapterRequestToJSON(json: any): CourseApiDeleteChapterRequest {
      return CourseApiDeleteChapterRequestToJSONTyped(json, false);
  }

  export function CourseApiDeleteChapterRequestToJSONTyped(value?: CourseApiDeleteChapterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
    };
}

