/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseApiCreateCourseResponse } from './CourseApiCreateCourseResponse';
import {
    CourseApiCreateCourseResponseFromJSON,
    CourseApiCreateCourseResponseFromJSONTyped,
    CourseApiCreateCourseResponseToJSON,
    CourseApiCreateCourseResponseToJSONTyped,
} from './CourseApiCreateCourseResponse';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';

/**
 * 
 * @export
 * @interface CourseCreateCoursePost200Response
 */
export interface CourseCreateCoursePost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseCreateCoursePost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiCreateCourseResponse}
     * @memberof CourseCreateCoursePost200Response
     */
    data?: CourseApiCreateCourseResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseCreateCoursePost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseCreateCoursePost200Response interface.
 */
export function instanceOfCourseCreateCoursePost200Response(value: object): value is CourseCreateCoursePost200Response {
    return true;
}

export function CourseCreateCoursePost200ResponseFromJSON(json: any): CourseCreateCoursePost200Response {
    return CourseCreateCoursePost200ResponseFromJSONTyped(json, false);
}

export function CourseCreateCoursePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseCreateCoursePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiCreateCourseResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseCreateCoursePost200ResponseToJSON(json: any): CourseCreateCoursePost200Response {
      return CourseCreateCoursePost200ResponseToJSONTyped(json, false);
  }

  export function CourseCreateCoursePost200ResponseToJSONTyped(value?: CourseCreateCoursePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiCreateCourseResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

