/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiCreateChapterRequest
 */
export interface CourseApiCreateChapterRequest {
    /**
     * 
     * @type {string}
     * @memberof CourseApiCreateChapterRequest
     */
    chapterName?: string;
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateChapterRequest
     */
    courseID?: number;
    /**
     * 
     * @type {string}
     * @memberof CourseApiCreateChapterRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateChapterRequest
     */
    difficulty?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateChapterRequest
     */
    index?: number;
}

/**
 * Check if a given object implements the CourseApiCreateChapterRequest interface.
 */
export function instanceOfCourseApiCreateChapterRequest(value: object): value is CourseApiCreateChapterRequest {
    return true;
}

export function CourseApiCreateChapterRequestFromJSON(json: any): CourseApiCreateChapterRequest {
    return CourseApiCreateChapterRequestFromJSONTyped(json, false);
}

export function CourseApiCreateChapterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiCreateChapterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterName': json['chapterName'] == null ? undefined : json['chapterName'],
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'index': json['index'] == null ? undefined : json['index'],
    };
}

  export function CourseApiCreateChapterRequestToJSON(json: any): CourseApiCreateChapterRequest {
      return CourseApiCreateChapterRequestToJSONTyped(json, false);
  }

  export function CourseApiCreateChapterRequestToJSONTyped(value?: CourseApiCreateChapterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterName': value['chapterName'],
        'courseID': value['courseID'],
        'description': value['description'],
        'difficulty': value['difficulty'],
        'index': value['index'],
    };
}

