/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiUpdateCourseRequest
 */
export interface CourseApiUpdateCourseRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiUpdateCourseRequest
     */
    courseID?: number;
    /**
     * 
     * @type {string}
     * @memberof CourseApiUpdateCourseRequest
     */
    courseName?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseApiUpdateCourseRequest
     */
    cover?: string;
    /**
     * 
     * @type {string}
     * @memberof CourseApiUpdateCourseRequest
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof CourseApiUpdateCourseRequest
     */
    createrID?: number;
    /**
     * 
     * @type {string}
     * @memberof CourseApiUpdateCourseRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CourseApiUpdateCourseRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the CourseApiUpdateCourseRequest interface.
 */
export function instanceOfCourseApiUpdateCourseRequest(value: object): value is CourseApiUpdateCourseRequest {
    return true;
}

export function CourseApiUpdateCourseRequestFromJSON(json: any): CourseApiUpdateCourseRequest {
    return CourseApiUpdateCourseRequestFromJSONTyped(json, false);
}

export function CourseApiUpdateCourseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiUpdateCourseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'courseName': json['courseName'] == null ? undefined : json['courseName'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'createrID': json['createrID'] == null ? undefined : json['createrID'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

  export function CourseApiUpdateCourseRequestToJSON(json: any): CourseApiUpdateCourseRequest {
      return CourseApiUpdateCourseRequestToJSONTyped(json, false);
  }

  export function CourseApiUpdateCourseRequestToJSONTyped(value?: CourseApiUpdateCourseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
        'courseName': value['courseName'],
        'cover': value['cover'],
        'createdAt': value['createdAt'],
        'createrID': value['createrID'],
        'description': value['description'],
        'id': value['id'],
    };
}

