/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsCourseModel } from './ModelsCourseModel';
import {
    ModelsCourseModelFromJSON,
    ModelsCourseModelFromJSONTyped,
    ModelsCourseModelToJSON,
    ModelsCourseModelToJSONTyped,
} from './ModelsCourseModel';

/**
 * 
 * @export
 * @interface CourseApiGetCourseResponse
 */
export interface CourseApiGetCourseResponse {
    /**
     * 
     * @type {ModelsCourseModel}
     * @memberof CourseApiGetCourseResponse
     */
    course?: ModelsCourseModel;
}

/**
 * Check if a given object implements the CourseApiGetCourseResponse interface.
 */
export function instanceOfCourseApiGetCourseResponse(value: object): value is CourseApiGetCourseResponse {
    return true;
}

export function CourseApiGetCourseResponseFromJSON(json: any): CourseApiGetCourseResponse {
    return CourseApiGetCourseResponseFromJSONTyped(json, false);
}

export function CourseApiGetCourseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetCourseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'course': json['course'] == null ? undefined : ModelsCourseModelFromJSON(json['course']),
    };
}

  export function CourseApiGetCourseResponseToJSON(json: any): CourseApiGetCourseResponse {
      return CourseApiGetCourseResponseToJSONTyped(json, false);
  }

  export function CourseApiGetCourseResponseToJSONTyped(value?: CourseApiGetCourseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'course': ModelsCourseModelToJSON(value['course']),
    };
}

