/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGetChaptersByUserIDRequest
 */
export interface CourseApiGetChaptersByUserIDRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGetChaptersByUserIDRequest
     */
    courseID?: number;
}

/**
 * Check if a given object implements the CourseApiGetChaptersByUserIDRequest interface.
 */
export function instanceOfCourseApiGetChaptersByUserIDRequest(value: object): value is CourseApiGetChaptersByUserIDRequest {
    return true;
}

export function CourseApiGetChaptersByUserIDRequestFromJSON(json: any): CourseApiGetChaptersByUserIDRequest {
    return CourseApiGetChaptersByUserIDRequestFromJSONTyped(json, false);
}

export function CourseApiGetChaptersByUserIDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetChaptersByUserIDRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
    };
}

  export function CourseApiGetChaptersByUserIDRequestToJSON(json: any): CourseApiGetChaptersByUserIDRequest {
      return CourseApiGetChaptersByUserIDRequestToJSONTyped(json, false);
  }

  export function CourseApiGetChaptersByUserIDRequestToJSONTyped(value?: CourseApiGetChaptersByUserIDRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
    };
}

