/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseApiCourseUserInfo } from './CourseApiCourseUserInfo';
import {
    CourseApiCourseUserInfoFromJSON,
    CourseApiCourseUserInfoFromJSONTyped,
    CourseApiCourseUserInfoToJSON,
    CourseApiCourseUserInfoToJSONTyped,
} from './CourseApiCourseUserInfo';

/**
 * 
 * @export
 * @interface CourseApiGetCourseStudentsResponse
 */
export interface CourseApiGetCourseStudentsResponse {
    /**
     * 
     * @type {Array<CourseApiCourseUserInfo>}
     * @memberof CourseApiGetCourseStudentsResponse
     */
    user_infos?: Array<CourseApiCourseUserInfo>;
}

/**
 * Check if a given object implements the CourseApiGetCourseStudentsResponse interface.
 */
export function instanceOfCourseApiGetCourseStudentsResponse(value: object): value is CourseApiGetCourseStudentsResponse {
    return true;
}

export function CourseApiGetCourseStudentsResponseFromJSON(json: any): CourseApiGetCourseStudentsResponse {
    return CourseApiGetCourseStudentsResponseFromJSONTyped(json, false);
}

export function CourseApiGetCourseStudentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGetCourseStudentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user_infos': json['user_infos'] == null ? undefined : ((json['user_infos'] as Array<any>).map(CourseApiCourseUserInfoFromJSON)),
    };
}

  export function CourseApiGetCourseStudentsResponseToJSON(json: any): CourseApiGetCourseStudentsResponse {
      return CourseApiGetCourseStudentsResponseToJSONTyped(json, false);
  }

  export function CourseApiGetCourseStudentsResponseToJSONTyped(value?: CourseApiGetCourseStudentsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_infos': value['user_infos'] == null ? undefined : ((value['user_infos'] as Array<any>).map(CourseApiCourseUserInfoToJSON)),
    };
}

