/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { CourseApiGenChapterScoreResponse } from './CourseApiGenChapterScoreResponse';
import {
    CourseApiGenChapterScoreResponseFromJSON,
    CourseApiGenChapterScoreResponseFromJSONTyped,
    CourseApiGenChapterScoreResponseToJSON,
    CourseApiGenChapterScoreResponseToJSONTyped,
} from './CourseApiGenChapterScoreResponse';

/**
 * 
 * @export
 * @interface CourseGenChapterScorePost200Response
 */
export interface CourseGenChapterScorePost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseGenChapterScorePost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiGenChapterScoreResponse}
     * @memberof CourseGenChapterScorePost200Response
     */
    data?: CourseApiGenChapterScoreResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseGenChapterScorePost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseGenChapterScorePost200Response interface.
 */
export function instanceOfCourseGenChapterScorePost200Response(value: object): value is CourseGenChapterScorePost200Response {
    return true;
}

export function CourseGenChapterScorePost200ResponseFromJSON(json: any): CourseGenChapterScorePost200Response {
    return CourseGenChapterScorePost200ResponseFromJSONTyped(json, false);
}

export function CourseGenChapterScorePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseGenChapterScorePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiGenChapterScoreResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseGenChapterScorePost200ResponseToJSON(json: any): CourseGenChapterScorePost200Response {
      return CourseGenChapterScorePost200ResponseToJSONTyped(json, false);
  }

  export function CourseGenChapterScorePost200ResponseToJSONTyped(value?: CourseGenChapterScorePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiGenChapterScoreResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

