/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiCreateConversationResponse
 */
export interface CourseApiCreateConversationResponse {
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateConversationResponse
     */
    conversationID?: number;
}

/**
 * Check if a given object implements the CourseApiCreateConversationResponse interface.
 */
export function instanceOfCourseApiCreateConversationResponse(value: object): value is CourseApiCreateConversationResponse {
    return true;
}

export function CourseApiCreateConversationResponseFromJSON(json: any): CourseApiCreateConversationResponse {
    return CourseApiCreateConversationResponseFromJSONTyped(json, false);
}

export function CourseApiCreateConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiCreateConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationID': json['conversationID'] == null ? undefined : json['conversationID'],
    };
}

  export function CourseApiCreateConversationResponseToJSON(json: any): CourseApiCreateConversationResponse {
      return CourseApiCreateConversationResponseToJSONTyped(json, false);
  }

  export function CourseApiCreateConversationResponseToJSONTyped(value?: CourseApiCreateConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationID': value['conversationID'],
    };
}

