/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiGenCourseFinishRequest
 */
export interface CourseApiGenCourseFinishRequest {
    /**
     * 
     * @type {number}
     * @memberof CourseApiGenCourseFinishRequest
     */
    courseID?: number;
    /**
     * 
     * @type {number}
     * @memberof CourseApiGenCourseFinishRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the CourseApiGenCourseFinishRequest interface.
 */
export function instanceOfCourseApiGenCourseFinishRequest(value: object): value is CourseApiGenCourseFinishRequest {
    return true;
}

export function CourseApiGenCourseFinishRequestFromJSON(json: any): CourseApiGenCourseFinishRequest {
    return CourseApiGenCourseFinishRequestFromJSONTyped(json, false);
}

export function CourseApiGenCourseFinishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiGenCourseFinishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function CourseApiGenCourseFinishRequestToJSON(json: any): CourseApiGenCourseFinishRequest {
      return CourseApiGenCourseFinishRequestToJSONTyped(json, false);
  }

  export function CourseApiGenCourseFinishRequestToJSONTyped(value?: CourseApiGenCourseFinishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
        'userID': value['userID'],
    };
}

