/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { CourseApiGetChaptersByUserIDResponse } from './CourseApiGetChaptersByUserIDResponse';
import {
    CourseApiGetChaptersByUserIDResponseFromJSON,
    CourseApiGetChaptersByUserIDResponseFromJSONTyped,
    CourseApiGetChaptersByUserIDResponseToJSON,
    CourseApiGetChaptersByUserIDResponseToJSONTyped,
} from './CourseApiGetChaptersByUserIDResponse';

/**
 * 
 * @export
 * @interface CourseGetChaptersByUserIdPost200Response
 */
export interface CourseGetChaptersByUserIdPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseGetChaptersByUserIdPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiGetChaptersByUserIDResponse}
     * @memberof CourseGetChaptersByUserIdPost200Response
     */
    data?: CourseApiGetChaptersByUserIDResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseGetChaptersByUserIdPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseGetChaptersByUserIdPost200Response interface.
 */
export function instanceOfCourseGetChaptersByUserIdPost200Response(value: object): value is CourseGetChaptersByUserIdPost200Response {
    return true;
}

export function CourseGetChaptersByUserIdPost200ResponseFromJSON(json: any): CourseGetChaptersByUserIdPost200Response {
    return CourseGetChaptersByUserIdPost200ResponseFromJSONTyped(json, false);
}

export function CourseGetChaptersByUserIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseGetChaptersByUserIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiGetChaptersByUserIDResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseGetChaptersByUserIdPost200ResponseToJSON(json: any): CourseGetChaptersByUserIdPost200Response {
      return CourseGetChaptersByUserIdPost200ResponseToJSONTyped(json, false);
  }

  export function CourseGetChaptersByUserIdPost200ResponseToJSONTyped(value?: CourseGetChaptersByUserIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiGetChaptersByUserIDResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

