/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseApiCreateCourseResponse
 */
export interface CourseApiCreateCourseResponse {
    /**
     * 
     * @type {number}
     * @memberof CourseApiCreateCourseResponse
     */
    courseID?: number;
}

/**
 * Check if a given object implements the CourseApiCreateCourseResponse interface.
 */
export function instanceOfCourseApiCreateCourseResponse(value: object): value is CourseApiCreateCourseResponse {
    return true;
}

export function CourseApiCreateCourseResponseFromJSON(json: any): CourseApiCreateCourseResponse {
    return CourseApiCreateCourseResponseFromJSONTyped(json, false);
}

export function CourseApiCreateCourseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseApiCreateCourseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
    };
}

  export function CourseApiCreateCourseResponseToJSON(json: any): CourseApiCreateCourseResponse {
      return CourseApiCreateCourseResponseToJSONTyped(json, false);
  }

  export function CourseApiCreateCourseResponseToJSONTyped(value?: CourseApiCreateCourseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseID': value['courseID'],
    };
}

