/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { CourseApiCreateConversationResponse } from './CourseApiCreateConversationResponse';
import {
    CourseApiCreateConversationResponseFromJSON,
    CourseApiCreateConversationResponseFromJSONTyped,
    CourseApiCreateConversationResponseToJSON,
    CourseApiCreateConversationResponseToJSONTyped,
} from './CourseApiCreateConversationResponse';

/**
 * 
 * @export
 * @interface CourseCreateConversationPost200Response
 */
export interface CourseCreateConversationPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof CourseCreateConversationPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {CourseApiCreateConversationResponse}
     * @memberof CourseCreateConversationPost200Response
     */
    data?: CourseApiCreateConversationResponse;
    /**
     * 
     * @type {string}
     * @memberof CourseCreateConversationPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the CourseCreateConversationPost200Response interface.
 */
export function instanceOfCourseCreateConversationPost200Response(value: object): value is CourseCreateConversationPost200Response {
    return true;
}

export function CourseCreateConversationPost200ResponseFromJSON(json: any): CourseCreateConversationPost200Response {
    return CourseCreateConversationPost200ResponseFromJSONTyped(json, false);
}

export function CourseCreateConversationPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseCreateConversationPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CourseApiCreateConversationResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function CourseCreateConversationPost200ResponseToJSON(json: any): CourseCreateConversationPost200Response {
      return CourseCreateConversationPost200ResponseToJSONTyped(json, false);
  }

  export function CourseCreateConversationPost200ResponseToJSONTyped(value?: CourseCreateConversationPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': CourseApiCreateConversationResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

