/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CtypeRole = {
    UnLoginRole: 0,
    AdminRole: 1,
    AuthRole: 2
} as const;
export type CtypeRole = typeof CtypeRole[keyof typeof CtypeRole];


export function instanceOfCtypeRole(value: any): boolean {
    for (const key in CtypeRole) {
        if (Object.prototype.hasOwnProperty.call(CtypeRole, key)) {
            if (CtypeRole[key as keyof typeof CtypeRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CtypeRoleFromJSON(json: any): CtypeRole {
    return CtypeRoleFromJSONTyped(json, false);
}

export function CtypeRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): CtypeRole {
    return json as CtypeRole;
}

export function CtypeRoleToJSON(value?: CtypeRole | null): any {
    return value as any;
}

export function CtypeRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): CtypeRole {
    return value as CtypeRole;
}

