/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { ImageApiImageListResponse } from './ImageApiImageListResponse';
import {
    ImageApiImageListResponseFromJSON,
    ImageApiImageListResponseFromJSONTyped,
    ImageApiImageListResponseToJSON,
    ImageApiImageListResponseToJSONTyped,
} from './ImageApiImageListResponse';

/**
 * 
 * @export
 * @interface ImageGet200Response
 */
export interface ImageGet200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof ImageGet200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {Array<ImageApiImageListResponse>}
     * @memberof ImageGet200Response
     */
    data?: Array<ImageApiImageListResponse>;
    /**
     * 
     * @type {string}
     * @memberof ImageGet200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the ImageGet200Response interface.
 */
export function instanceOfImageGet200Response(value: object): value is ImageGet200Response {
    return true;
}

export function ImageGet200ResponseFromJSON(json: any): ImageGet200Response {
    return ImageGet200ResponseFromJSONTyped(json, false);
}

export function ImageGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ImageApiImageListResponseFromJSON)),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function ImageGet200ResponseToJSON(json: any): ImageGet200Response {
      return ImageGet200ResponseToJSONTyped(json, false);
  }

  export function ImageGet200ResponseToJSONTyped(value?: ImageGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ImageApiImageListResponseToJSON)),
        'msg': value['msg'],
    };
}

