/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { MessageApiResetConversationResponse } from './MessageApiResetConversationResponse';
import {
    MessageApiResetConversationResponseFromJSON,
    MessageApiResetConversationResponseFromJSONTyped,
    MessageApiResetConversationResponseToJSON,
    MessageApiResetConversationResponseToJSONTyped,
} from './MessageApiResetConversationResponse';

/**
 * 
 * @export
 * @interface MessageResetConversationPost200Response
 */
export interface MessageResetConversationPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof MessageResetConversationPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {MessageApiResetConversationResponse}
     * @memberof MessageResetConversationPost200Response
     */
    data?: MessageApiResetConversationResponse;
    /**
     * 
     * @type {string}
     * @memberof MessageResetConversationPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the MessageResetConversationPost200Response interface.
 */
export function instanceOfMessageResetConversationPost200Response(value: object): value is MessageResetConversationPost200Response {
    return true;
}

export function MessageResetConversationPost200ResponseFromJSON(json: any): MessageResetConversationPost200Response {
    return MessageResetConversationPost200ResponseFromJSONTyped(json, false);
}

export function MessageResetConversationPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageResetConversationPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : MessageApiResetConversationResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function MessageResetConversationPost200ResponseToJSON(json: any): MessageResetConversationPost200Response {
      return MessageResetConversationPost200ResponseToJSONTyped(json, false);
  }

  export function MessageResetConversationPost200ResponseToJSONTyped(value?: MessageResetConversationPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': MessageApiResetConversationResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

