/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiGetConversationIDResponse
 */
export interface MessageApiGetConversationIDResponse {
    /**
     * 
     * @type {number}
     * @memberof MessageApiGetConversationIDResponse
     */
    conversationID?: number;
}

/**
 * Check if a given object implements the MessageApiGetConversationIDResponse interface.
 */
export function instanceOfMessageApiGetConversationIDResponse(value: object): value is MessageApiGetConversationIDResponse {
    return true;
}

export function MessageApiGetConversationIDResponseFromJSON(json: any): MessageApiGetConversationIDResponse {
    return MessageApiGetConversationIDResponseFromJSONTyped(json, false);
}

export function MessageApiGetConversationIDResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiGetConversationIDResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationID': json['conversationID'] == null ? undefined : json['conversationID'],
    };
}

  export function MessageApiGetConversationIDResponseToJSON(json: any): MessageApiGetConversationIDResponse {
      return MessageApiGetConversationIDResponseToJSONTyped(json, false);
  }

  export function MessageApiGetConversationIDResponseToJSONTyped(value?: MessageApiGetConversationIDResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationID': value['conversationID'],
    };
}

