/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { MessageApiCreateConversationResponse } from './MessageApiCreateConversationResponse';
import {
    MessageApiCreateConversationResponseFromJSON,
    MessageApiCreateConversationResponseFromJSONTyped,
    MessageApiCreateConversationResponseToJSON,
    MessageApiCreateConversationResponseToJSONTyped,
} from './MessageApiCreateConversationResponse';

/**
 * 
 * @export
 * @interface MessageCreateConversationPost200Response
 */
export interface MessageCreateConversationPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof MessageCreateConversationPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {MessageApiCreateConversationResponse}
     * @memberof MessageCreateConversationPost200Response
     */
    data?: MessageApiCreateConversationResponse;
    /**
     * 
     * @type {string}
     * @memberof MessageCreateConversationPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the MessageCreateConversationPost200Response interface.
 */
export function instanceOfMessageCreateConversationPost200Response(value: object): value is MessageCreateConversationPost200Response {
    return true;
}

export function MessageCreateConversationPost200ResponseFromJSON(json: any): MessageCreateConversationPost200Response {
    return MessageCreateConversationPost200ResponseFromJSONTyped(json, false);
}

export function MessageCreateConversationPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageCreateConversationPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : MessageApiCreateConversationResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function MessageCreateConversationPost200ResponseToJSON(json: any): MessageCreateConversationPost200Response {
      return MessageCreateConversationPost200ResponseToJSONTyped(json, false);
  }

  export function MessageCreateConversationPost200ResponseToJSONTyped(value?: MessageCreateConversationPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': MessageApiCreateConversationResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

