/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsMessageModel } from './ModelsMessageModel';
import {
    ModelsMessageModelFromJSON,
    ModelsMessageModelFromJSONTyped,
    ModelsMessageModelToJSON,
    ModelsMessageModelToJSONTyped,
} from './ModelsMessageModel';

/**
 * 
 * @export
 * @interface MessageApiGetHistoryMsgResponse
 */
export interface MessageApiGetHistoryMsgResponse {
    /**
     * 
     * @type {Array<ModelsMessageModel>}
     * @memberof MessageApiGetHistoryMsgResponse
     */
    message_list?: Array<ModelsMessageModel>;
}

/**
 * Check if a given object implements the MessageApiGetHistoryMsgResponse interface.
 */
export function instanceOfMessageApiGetHistoryMsgResponse(value: object): value is MessageApiGetHistoryMsgResponse {
    return true;
}

export function MessageApiGetHistoryMsgResponseFromJSON(json: any): MessageApiGetHistoryMsgResponse {
    return MessageApiGetHistoryMsgResponseFromJSONTyped(json, false);
}

export function MessageApiGetHistoryMsgResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiGetHistoryMsgResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message_list': json['message_list'] == null ? undefined : ((json['message_list'] as Array<any>).map(ModelsMessageModelFromJSON)),
    };
}

  export function MessageApiGetHistoryMsgResponseToJSON(json: any): MessageApiGetHistoryMsgResponse {
      return MessageApiGetHistoryMsgResponseToJSONTyped(json, false);
  }

  export function MessageApiGetHistoryMsgResponseToJSONTyped(value?: MessageApiGetHistoryMsgResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message_list': value['message_list'] == null ? undefined : ((value['message_list'] as Array<any>).map(ModelsMessageModelToJSON)),
    };
}

