/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiCreateConversationRequest
 */
export interface MessageApiCreateConversationRequest {
    /**
     * 
     * @type {number}
     * @memberof MessageApiCreateConversationRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageApiCreateConversationRequest
     */
    courseID?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageApiCreateConversationRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the MessageApiCreateConversationRequest interface.
 */
export function instanceOfMessageApiCreateConversationRequest(value: object): value is MessageApiCreateConversationRequest {
    return true;
}

export function MessageApiCreateConversationRequestFromJSON(json: any): MessageApiCreateConversationRequest {
    return MessageApiCreateConversationRequestFromJSONTyped(json, false);
}

export function MessageApiCreateConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiCreateConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function MessageApiCreateConversationRequestToJSON(json: any): MessageApiCreateConversationRequest {
      return MessageApiCreateConversationRequestToJSONTyped(json, false);
  }

  export function MessageApiCreateConversationRequestToJSONTyped(value?: MessageApiCreateConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'courseID': value['courseID'],
        'userID': value['userID'],
    };
}

