/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { MessageApiSendMsgResponse } from './MessageApiSendMsgResponse';
import {
    MessageApiSendMsgResponseFromJSON,
    MessageApiSendMsgResponseFromJSONTyped,
    MessageApiSendMsgResponseToJSON,
    MessageApiSendMsgResponseToJSONTyped,
} from './MessageApiSendMsgResponse';

/**
 * 
 * @export
 * @interface MessageSendMsgPost200Response
 */
export interface MessageSendMsgPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof MessageSendMsgPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {MessageApiSendMsgResponse}
     * @memberof MessageSendMsgPost200Response
     */
    data?: MessageApiSendMsgResponse;
    /**
     * 
     * @type {string}
     * @memberof MessageSendMsgPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the MessageSendMsgPost200Response interface.
 */
export function instanceOfMessageSendMsgPost200Response(value: object): value is MessageSendMsgPost200Response {
    return true;
}

export function MessageSendMsgPost200ResponseFromJSON(json: any): MessageSendMsgPost200Response {
    return MessageSendMsgPost200ResponseFromJSONTyped(json, false);
}

export function MessageSendMsgPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageSendMsgPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : MessageApiSendMsgResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function MessageSendMsgPost200ResponseToJSON(json: any): MessageSendMsgPost200Response {
      return MessageSendMsgPost200ResponseToJSONTyped(json, false);
  }

  export function MessageSendMsgPost200ResponseToJSONTyped(value?: MessageSendMsgPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': MessageApiSendMsgResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

