/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiResetConversationRequest
 */
export interface MessageApiResetConversationRequest {
    /**
     * 
     * @type {number}
     * @memberof MessageApiResetConversationRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageApiResetConversationRequest
     */
    courseID?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageApiResetConversationRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the MessageApiResetConversationRequest interface.
 */
export function instanceOfMessageApiResetConversationRequest(value: object): value is MessageApiResetConversationRequest {
    return true;
}

export function MessageApiResetConversationRequestFromJSON(json: any): MessageApiResetConversationRequest {
    return MessageApiResetConversationRequestFromJSONTyped(json, false);
}

export function MessageApiResetConversationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiResetConversationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function MessageApiResetConversationRequestToJSON(json: any): MessageApiResetConversationRequest {
      return MessageApiResetConversationRequestToJSONTyped(json, false);
  }

  export function MessageApiResetConversationRequestToJSONTyped(value?: MessageApiResetConversationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'courseID': value['courseID'],
        'userID': value['userID'],
    };
}

