/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiSendMsgResponse
 */
export interface MessageApiSendMsgResponse {
    /**
     * 
     * @type {string}
     * @memberof MessageApiSendMsgResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the MessageApiSendMsgResponse interface.
 */
export function instanceOfMessageApiSendMsgResponse(value: object): value is MessageApiSendMsgResponse {
    return true;
}

export function MessageApiSendMsgResponseFromJSON(json: any): MessageApiSendMsgResponse {
    return MessageApiSendMsgResponseFromJSONTyped(json, false);
}

export function MessageApiSendMsgResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiSendMsgResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

  export function MessageApiSendMsgResponseToJSON(json: any): MessageApiSendMsgResponse {
      return MessageApiSendMsgResponseToJSONTyped(json, false);
  }

  export function MessageApiSendMsgResponseToJSONTyped(value?: MessageApiSendMsgResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

