/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiSendMsgRequest
 */
export interface MessageApiSendMsgRequest {
    /**
     * 
     * @type {number}
     * @memberof MessageApiSendMsgRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {string}
     * @memberof MessageApiSendMsgRequest
     */
    content?: string;
    /**
     * 
     * @type {number}
     * @memberof MessageApiSendMsgRequest
     */
    courseID?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageApiSendMsgRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the MessageApiSendMsgRequest interface.
 */
export function instanceOfMessageApiSendMsgRequest(value: object): value is MessageApiSendMsgRequest {
    return true;
}

export function MessageApiSendMsgRequestFromJSON(json: any): MessageApiSendMsgRequest {
    return MessageApiSendMsgRequestFromJSONTyped(json, false);
}

export function MessageApiSendMsgRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiSendMsgRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'content': json['content'] == null ? undefined : json['content'],
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function MessageApiSendMsgRequestToJSON(json: any): MessageApiSendMsgRequest {
      return MessageApiSendMsgRequestToJSONTyped(json, false);
  }

  export function MessageApiSendMsgRequestToJSONTyped(value?: MessageApiSendMsgRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'content': value['content'],
        'courseID': value['courseID'],
        'userID': value['userID'],
    };
}

