/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiResetConversationResponse
 */
export interface MessageApiResetConversationResponse {
    /**
     * 
     * @type {number}
     * @memberof MessageApiResetConversationResponse
     */
    conversationID?: number;
}

/**
 * Check if a given object implements the MessageApiResetConversationResponse interface.
 */
export function instanceOfMessageApiResetConversationResponse(value: object): value is MessageApiResetConversationResponse {
    return true;
}

export function MessageApiResetConversationResponseFromJSON(json: any): MessageApiResetConversationResponse {
    return MessageApiResetConversationResponseFromJSONTyped(json, false);
}

export function MessageApiResetConversationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiResetConversationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversationID': json['conversationID'] == null ? undefined : json['conversationID'],
    };
}

  export function MessageApiResetConversationResponseToJSON(json: any): MessageApiResetConversationResponse {
      return MessageApiResetConversationResponseToJSONTyped(json, false);
  }

  export function MessageApiResetConversationResponseToJSONTyped(value?: MessageApiResetConversationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversationID': value['conversationID'],
    };
}

