/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { MessageApiGetConversationIDResponse } from './MessageApiGetConversationIDResponse';
import {
    MessageApiGetConversationIDResponseFromJSON,
    MessageApiGetConversationIDResponseFromJSONTyped,
    MessageApiGetConversationIDResponseToJSON,
    MessageApiGetConversationIDResponseToJSONTyped,
} from './MessageApiGetConversationIDResponse';

/**
 * 
 * @export
 * @interface MessageGetConversationIdPost200Response
 */
export interface MessageGetConversationIdPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof MessageGetConversationIdPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {MessageApiGetConversationIDResponse}
     * @memberof MessageGetConversationIdPost200Response
     */
    data?: MessageApiGetConversationIDResponse;
    /**
     * 
     * @type {string}
     * @memberof MessageGetConversationIdPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the MessageGetConversationIdPost200Response interface.
 */
export function instanceOfMessageGetConversationIdPost200Response(value: object): value is MessageGetConversationIdPost200Response {
    return true;
}

export function MessageGetConversationIdPost200ResponseFromJSON(json: any): MessageGetConversationIdPost200Response {
    return MessageGetConversationIdPost200ResponseFromJSONTyped(json, false);
}

export function MessageGetConversationIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageGetConversationIdPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : MessageApiGetConversationIDResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function MessageGetConversationIdPost200ResponseToJSON(json: any): MessageGetConversationIdPost200Response {
      return MessageGetConversationIdPost200ResponseToJSONTyped(json, false);
  }

  export function MessageGetConversationIdPost200ResponseToJSONTyped(value?: MessageGetConversationIdPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': MessageApiGetConversationIDResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

