/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageApiGetConversationIDRequest
 */
export interface MessageApiGetConversationIDRequest {
    /**
     * 
     * @type {number}
     * @memberof MessageApiGetConversationIDRequest
     */
    chapterID?: number;
    /**
     * 
     * @type {number}
     * @memberof MessageApiGetConversationIDRequest
     */
    userID?: number;
}

/**
 * Check if a given object implements the MessageApiGetConversationIDRequest interface.
 */
export function instanceOfMessageApiGetConversationIDRequest(value: object): value is MessageApiGetConversationIDRequest {
    return true;
}

export function MessageApiGetConversationIDRequestFromJSON(json: any): MessageApiGetConversationIDRequest {
    return MessageApiGetConversationIDRequestFromJSONTyped(json, false);
}

export function MessageApiGetConversationIDRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageApiGetConversationIDRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

  export function MessageApiGetConversationIDRequestToJSON(json: any): MessageApiGetConversationIDRequest {
      return MessageApiGetConversationIDRequestToJSONTyped(json, false);
  }

  export function MessageApiGetConversationIDRequestToJSONTyped(value?: MessageApiGetConversationIDRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'userID': value['userID'],
    };
}

