/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsChapterModel
 */
export interface ModelsChapterModel {
    /**
     * 章节ID
     * @type {number}
     * @memberof ModelsChapterModel
     */
    chapterID?: number;
    /**
     * 章节名称
     * @type {string}
     * @memberof ModelsChapterModel
     */
    chapterName?: string;
    /**
     * 课程ID
     * @type {number}
     * @memberof ModelsChapterModel
     */
    courseID?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsChapterModel
     */
    createdAt?: string;
    /**
     * 章节描述
     * @type {string}
     * @memberof ModelsChapterModel
     */
    description?: string;
    /**
     * 难度 1 简单 2 中等 3 困难
     * @type {number}
     * @memberof ModelsChapterModel
     */
    difficulty?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsChapterModel
     */
    id?: number;
    /**
     * 章节序号
     * @type {number}
     * @memberof ModelsChapterModel
     */
    index?: number;
}

/**
 * Check if a given object implements the ModelsChapterModel interface.
 */
export function instanceOfModelsChapterModel(value: object): value is ModelsChapterModel {
    return true;
}

export function ModelsChapterModelFromJSON(json: any): ModelsChapterModel {
    return ModelsChapterModelFromJSONTyped(json, false);
}

export function ModelsChapterModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsChapterModel {
    if (json == null) {
        return json;
    }
    return {
        
        'chapterID': json['chapterID'] == null ? undefined : json['chapterID'],
        'chapterName': json['chapterName'] == null ? undefined : json['chapterName'],
        'courseID': json['courseID'] == null ? undefined : json['courseID'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'id': json['id'] == null ? undefined : json['id'],
        'index': json['index'] == null ? undefined : json['index'],
    };
}

  export function ModelsChapterModelToJSON(json: any): ModelsChapterModel {
      return ModelsChapterModelToJSONTyped(json, false);
  }

  export function ModelsChapterModelToJSONTyped(value?: ModelsChapterModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapterID': value['chapterID'],
        'chapterName': value['chapterName'],
        'courseID': value['courseID'],
        'createdAt': value['createdAt'],
        'description': value['description'],
        'difficulty': value['difficulty'],
        'id': value['id'],
        'index': value['index'],
    };
}

