/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserApiLoginResponse
 */
export interface UserApiLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof UserApiLoginResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the UserApiLoginResponse interface.
 */
export function instanceOfUserApiLoginResponse(value: object): value is UserApiLoginResponse {
    return true;
}

export function UserApiLoginResponseFromJSON(json: any): UserApiLoginResponse {
    return UserApiLoginResponseFromJSONTyped(json, false);
}

export function UserApiLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function UserApiLoginResponseToJSON(json: any): UserApiLoginResponse {
      return UserApiLoginResponseToJSONTyped(json, false);
  }

  export function UserApiLoginResponseToJSONTyped(value?: UserApiLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

