/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsUserModel } from './ModelsUserModel';
import {
    ModelsUserModelFromJSON,
    ModelsUserModelFromJSONTyped,
    ModelsUserModelToJSON,
    ModelsUserModelToJSONTyped,
} from './ModelsUserModel';

/**
 * 
 * @export
 * @interface UserApiSetUserInfoRequest
 */
export interface UserApiSetUserInfoRequest {
    /**
     * 
     * @type {ModelsUserModel}
     * @memberof UserApiSetUserInfoRequest
     */
    userInfo?: ModelsUserModel;
}

/**
 * Check if a given object implements the UserApiSetUserInfoRequest interface.
 */
export function instanceOfUserApiSetUserInfoRequest(value: object): value is UserApiSetUserInfoRequest {
    return true;
}

export function UserApiSetUserInfoRequestFromJSON(json: any): UserApiSetUserInfoRequest {
    return UserApiSetUserInfoRequestFromJSONTyped(json, false);
}

export function UserApiSetUserInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiSetUserInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userInfo': json['userInfo'] == null ? undefined : ModelsUserModelFromJSON(json['userInfo']),
    };
}

  export function UserApiSetUserInfoRequestToJSON(json: any): UserApiSetUserInfoRequest {
      return UserApiSetUserInfoRequestToJSONTyped(json, false);
  }

  export function UserApiSetUserInfoRequestToJSONTyped(value?: UserApiSetUserInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userInfo': ModelsUserModelToJSON(value['userInfo']),
    };
}

