/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { UserApiGetUserInfoResponse } from './UserApiGetUserInfoResponse';
import {
    UserApiGetUserInfoResponseFromJSON,
    UserApiGetUserInfoResponseFromJSONTyped,
    UserApiGetUserInfoResponseToJSON,
    UserApiGetUserInfoResponseToJSONTyped,
} from './UserApiGetUserInfoResponse';

/**
 * 
 * @export
 * @interface UserGetUserInfoPost200Response
 */
export interface UserGetUserInfoPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof UserGetUserInfoPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {UserApiGetUserInfoResponse}
     * @memberof UserGetUserInfoPost200Response
     */
    data?: UserApiGetUserInfoResponse;
    /**
     * 
     * @type {string}
     * @memberof UserGetUserInfoPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the UserGetUserInfoPost200Response interface.
 */
export function instanceOfUserGetUserInfoPost200Response(value: object): value is UserGetUserInfoPost200Response {
    return true;
}

export function UserGetUserInfoPost200ResponseFromJSON(json: any): UserGetUserInfoPost200Response {
    return UserGetUserInfoPost200ResponseFromJSONTyped(json, false);
}

export function UserGetUserInfoPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGetUserInfoPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : UserApiGetUserInfoResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function UserGetUserInfoPost200ResponseToJSON(json: any): UserGetUserInfoPost200Response {
      return UserGetUserInfoPost200ResponseToJSONTyped(json, false);
  }

  export function UserGetUserInfoPost200ResponseToJSONTyped(value?: UserGetUserInfoPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': UserApiGetUserInfoResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

