/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { UserApiRegisterResponse } from './UserApiRegisterResponse';
import {
    UserApiRegisterResponseFromJSON,
    UserApiRegisterResponseFromJSONTyped,
    UserApiRegisterResponseToJSON,
    UserApiRegisterResponseToJSONTyped,
} from './UserApiRegisterResponse';

/**
 * 
 * @export
 * @interface UserRegisterPost200Response
 */
export interface UserRegisterPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof UserRegisterPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {UserApiRegisterResponse}
     * @memberof UserRegisterPost200Response
     */
    data?: UserApiRegisterResponse;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the UserRegisterPost200Response interface.
 */
export function instanceOfUserRegisterPost200Response(value: object): value is UserRegisterPost200Response {
    return true;
}

export function UserRegisterPost200ResponseFromJSON(json: any): UserRegisterPost200Response {
    return UserRegisterPost200ResponseFromJSONTyped(json, false);
}

export function UserRegisterPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : UserApiRegisterResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function UserRegisterPost200ResponseToJSON(json: any): UserRegisterPost200Response {
      return UserRegisterPost200ResponseToJSONTyped(json, false);
  }

  export function UserRegisterPost200ResponseToJSONTyped(value?: UserRegisterPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': UserApiRegisterResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

