/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserApiRegisterResponse
 */
export interface UserApiRegisterResponse {
    /**
     * 
     * @type {string}
     * @memberof UserApiRegisterResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the UserApiRegisterResponse interface.
 */
export function instanceOfUserApiRegisterResponse(value: object): value is UserApiRegisterResponse {
    return true;
}

export function UserApiRegisterResponseFromJSON(json: any): UserApiRegisterResponse {
    return UserApiRegisterResponseFromJSONTyped(json, false);
}

export function UserApiRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

  export function UserApiRegisterResponseToJSON(json: any): UserApiRegisterResponse {
      return UserApiRegisterResponseToJSONTyped(json, false);
  }

  export function UserApiRegisterResponseToJSONTyped(value?: UserApiRegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

