/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsUserModel } from './ModelsUserModel';
import {
    ModelsUserModelFromJSON,
    ModelsUserModelFromJSONTyped,
    ModelsUserModelToJSON,
    ModelsUserModelToJSONTyped,
} from './ModelsUserModel';

/**
 * 
 * @export
 * @interface UserApiGetUserInfoResponse
 */
export interface UserApiGetUserInfoResponse {
    /**
     * 
     * @type {ModelsUserModel}
     * @memberof UserApiGetUserInfoResponse
     */
    userInfo?: ModelsUserModel;
}

/**
 * Check if a given object implements the UserApiGetUserInfoResponse interface.
 */
export function instanceOfUserApiGetUserInfoResponse(value: object): value is UserApiGetUserInfoResponse {
    return true;
}

export function UserApiGetUserInfoResponseFromJSON(json: any): UserApiGetUserInfoResponse {
    return UserApiGetUserInfoResponseFromJSONTyped(json, false);
}

export function UserApiGetUserInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiGetUserInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userInfo': json['userInfo'] == null ? undefined : ModelsUserModelFromJSON(json['userInfo']),
    };
}

  export function UserApiGetUserInfoResponseToJSON(json: any): UserApiGetUserInfoResponse {
      return UserApiGetUserInfoResponseToJSONTyped(json, false);
  }

  export function UserApiGetUserInfoResponseToJSONTyped(value?: UserApiGetUserInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userInfo': ModelsUserModelToJSON(value['userInfo']),
    };
}

