/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResCode } from './ResCode';
import {
    ResCodeFromJSON,
    ResCodeFromJSONTyped,
    ResCodeToJSON,
    ResCodeToJSONTyped,
} from './ResCode';
import type { UserApiSetUserInfoResponse } from './UserApiSetUserInfoResponse';
import {
    UserApiSetUserInfoResponseFromJSON,
    UserApiSetUserInfoResponseFromJSONTyped,
    UserApiSetUserInfoResponseToJSON,
    UserApiSetUserInfoResponseToJSONTyped,
} from './UserApiSetUserInfoResponse';

/**
 * 
 * @export
 * @interface UserSetUserInfoPost200Response
 */
export interface UserSetUserInfoPost200Response {
    /**
     * 业务状态码
     * @type {ResCode}
     * @memberof UserSetUserInfoPost200Response
     */
    code?: ResCode;
    /**
     * 
     * @type {UserApiSetUserInfoResponse}
     * @memberof UserSetUserInfoPost200Response
     */
    data?: UserApiSetUserInfoResponse;
    /**
     * 
     * @type {string}
     * @memberof UserSetUserInfoPost200Response
     */
    msg?: string;
}



/**
 * Check if a given object implements the UserSetUserInfoPost200Response interface.
 */
export function instanceOfUserSetUserInfoPost200Response(value: object): value is UserSetUserInfoPost200Response {
    return true;
}

export function UserSetUserInfoPost200ResponseFromJSON(json: any): UserSetUserInfoPost200Response {
    return UserSetUserInfoPost200ResponseFromJSONTyped(json, false);
}

export function UserSetUserInfoPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSetUserInfoPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ResCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : UserApiSetUserInfoResponseFromJSON(json['data']),
        'msg': json['msg'] == null ? undefined : json['msg'],
    };
}

  export function UserSetUserInfoPost200ResponseToJSON(json: any): UserSetUserInfoPost200Response {
      return UserSetUserInfoPost200ResponseToJSONTyped(json, false);
  }

  export function UserSetUserInfoPost200ResponseToJSONTyped(value?: UserSetUserInfoPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': ResCodeToJSON(value['code']),
        'data': UserApiSetUserInfoResponseToJSON(value['data']),
        'msg': value['msg'],
    };
}

