/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserApiSetUserInfoResponse
 */
export interface UserApiSetUserInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof UserApiSetUserInfoResponse
     */
    response?: string;
}

/**
 * Check if a given object implements the UserApiSetUserInfoResponse interface.
 */
export function instanceOfUserApiSetUserInfoResponse(value: object): value is UserApiSetUserInfoResponse {
    return true;
}

export function UserApiSetUserInfoResponseFromJSON(json: any): UserApiSetUserInfoResponse {
    return UserApiSetUserInfoResponseFromJSONTyped(json, false);
}

export function UserApiSetUserInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserApiSetUserInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : json['response'],
    };
}

  export function UserApiSetUserInfoResponseToJSON(json: any): UserApiSetUserInfoResponse {
      return UserApiSetUserInfoResponseToJSONTyped(json, false);
  }

  export function UserApiSetUserInfoResponseToJSONTyped(value?: UserApiSetUserInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'response': value['response'],
    };
}

